name: 'Kingly paragraph card'
type: 'Site'
description: 'Configures a Kingly card paragraph.'
recipes:
  - kingly_paragraph_media

install:
  - paragraphs
  - field_group
  - paragraph_view_mode
  - pathauto
  - lazy
  - options

config:
  strict: false
