# Attaches the body field to the Kingly Card paragraph type and configures its
# label, description, and allowed text formats.
langcode: en
status: true
dependencies:
  config:
    - field.storage.paragraph.field_card_body
    - filter.format.basic_html
    - paragraphs.paragraphs_type.kingly_paragraph_card
  module:
    - text
id: paragraph.kingly_paragraph_card.field_card_body
field_name: field_card_body
entity_type: paragraph
bundle: kingly_paragraph_card
label: 'Card body'
description: 'Enter the main text content for the card.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  allowed_formats:
    - basic_html
field_type: text_long
