# Updates the field instance to attach the image field to the new 'kingly_paragraph_card' bundle.
langcode: en
status: true
dependencies:
  config:
    - field.storage.paragraph.field_card_image
    - media.type.image
    - paragraphs.paragraphs_type.kingly_paragraph_card
id: paragraph.kingly_paragraph_card.field_card_image
field_name: field_card_image
entity_type: paragraph
bundle: kingly_paragraph_card
label: 'Card image'
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:media'
  handler_settings:
    target_bundles:
      image: image
    sort:
      field: _none
      direction: ASC
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
