# file: config/install/field.field.paragraph.kingly_paragraph_card.field_card_link.yml
# Attaches the link field to the Kingly Card paragraph type.
langcode: en
status: true
dependencies:
  config:
    - field.storage.paragraph.field_card_link
    - paragraphs.paragraphs_type.kingly_paragraph_card
  module:
    - link
id: paragraph.kingly_paragraph_card.field_card_link
field_name: field_card_link
entity_type: paragraph
bundle: kingly_paragraph_card
label: 'Card link'
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  title: 2
  link_type: 17
field_type: link
