# file: config/image.style.card_1800.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_1800
label: 'Card (1800w)'
effects:
  a4692861-9772-46ac-9026-30f6831c3b2f:
    uuid: a4692861-9772-46ac-9026-30f6831c3b2f
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 1800
      height: 1013
      crop_type: focal_point
  e1a547a7-f2ff-4046-8cff-7a439e95037c:
    uuid: e1a547a7-f2ff-4046-8cff-7a439e95037c
    id: image_convert
    weight: 2
    data:
      extension: webp
