# file: config/image.style.card_991.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_991
label: 'Card (991w)'
effects:
  74c1a539-7f31-4195-9733-415893d50f04:
    uuid: 74c1a539-7f31-4195-9733-415893d50f04
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 991
      height: 557
      crop_type: focal_point
  c61858a8-6512-4c2a-810a-20054c252a17:
    uuid: c61858a8-6512-4c2a-810a-20054c252a17
    id: image_convert
    weight: 2
    data:
      extension: webp
