# file: config/image.style.card_1280.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_1280
label: 'Card (1280w)'
effects:
  68916d1f-889c-4a34-a719-715103417088:
    uuid: 68916d1f-889c-4a34-a719-715103417088
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 1280
      height: 720
      crop_type: focal_point
  3e7a0273-0498-4223-9527-31952a65a32a:
    uuid: 3e7a0273-0498-4223-9527-31952a65a32a
    id: image_convert
    weight: 2
    data:
      extension: webp
