# file: config/image.style.card_1800.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_1800
label: 'Card (1800w)'
effects:
  8c9a8b7d-6e5f-4a3b-2c1d-0e9f8a7b6c5d:
    uuid: 8c9a8b7d-6e5f-4a3b-2c1d-0e9f8a7b6c5d
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 1800
      height: 1013
      crop_type: focal_point
  f1e2d3c4-b5a6-9878-8765-4321fedcba98:
    uuid: f1e2d3c4-b5a6-9878-8765-4321fedcba98
    id: image_convert
    weight: 2
    data:
      extension: webp
