# file: config/image.style.card_768.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_768
label: 'Card (768w)'
effects:
  0852e057-789e-4171-a20d-777085c88c03:
    uuid: 0852e057-789e-4171-a20d-777085c88c03
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 768
      height: 432
      crop_type: focal_point
  e123a49a-79b8-4c91-948f-3d1f05452f4c:
    uuid: e123a49a-79b8-4c91-948f-3d1f05452f4c
    id: image_convert
    weight: 2
    data:
      extension: webp
