# file: config/image.style.card_1280.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_1280
label: 'Card (1280w)'
effects:
  7f7660c1-38e2-45e0-888f-1d12b1860e0a:
    uuid: 7f7660c1-38e2-45e0-888f-1d12b1860e0a
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 1280
      height: 720
      crop_type: focal_point
  a0b1c2d3-e4f5-a6b7-c8d9-e0f1a2b3c4d5:
    uuid: a0b1c2d3-e4f5-a6b7-c8d9-e0f1a2b3c4d5
    id: image_convert
    weight: 2
    data:
      extension: webp
