# file: config/image.style.card_1800.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_1800
label: 'Card (1800w)'
effects:
  01234567-89ab-4cde-f012-3456789abcde:
    uuid: 01234567-89ab-4cde-f012-3456789abcde
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 1800
      height: 1013
      crop_type: focal_point
  fedcba98-7654-4321-fedc-ba9876543210:
    uuid: fedcba98-7654-4321-fedc-ba9876543210
    id: image_convert
    weight: 2
    data:
      extension: webp
