# file: config/image.style.card_1800.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_1800
label: 'Card (1800w)'
effects:
  b2f1c8a7-3e4d-5c6b-7a8d-9e0f1a2b3c4d:
    uuid: b2f1c8a7-3e4d-5c6b-7a8d-9e0f1a2b3c4d
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 1800
      height: 1013
      crop_type: focal_point
  e9f8d7c6-b5a4-3d2c-1b0a-9f8e7d6c5b4a:
    uuid: e9f8d7c6-b5a4-3d2c-1b0a-9f8e7d6c5b4a
    id: image_convert
    weight: 2
    data:
      extension: webp
