# file: config/image.style.card_991.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_991
label: 'Card (991w)'
effects:
  013e8954-41b4-4c7b-b056-b7e616f73752:
    uuid: 013e8954-41b4-4c7b-b056-b7e616f73752
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 991
      height: 557
      crop_type: focal_point
  9dd5f2d0-5231-419b-81d3-35f99222c815:
    uuid: 9dd5f2d0-5231-419b-81d3-35f99222c815
    id: image_convert
    weight: 2
    data:
      extension: webp
