# file: config/image.style.card_768.yml
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: card_768
label: 'Card (768w)'
effects:
  de71c0b8-9b88-4442-9937-238d58e39668:
    uuid: de71c0b8-9b88-4442-9937-238d58e39668
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 768
      height: 432
      crop_type: focal_point
  a9b1d7d8-ba9f-4b09-983e-a10c2834c56e:
    uuid: a9b1d7d8-ba9f-4b09-983e-a10c2834c56e
    id: image_convert
    weight: 2
    data:
      extension: webp
