# Renames the paragraph type to 'kingly_paragraph_card' for consistency and updates the label.
langcode: en
status: true
dependencies: {  }
id: kingly_paragraph_card
label: 'Kingly Card'
icon_uuid: null
icon_default: null
description: 'A responsive card with an image, title, body, and link, powered by a Single Directory Component.'
behavior_plugins: {  }
