# file: config/responsive_image.style.card_responsive.yml
langcode: en
status: true
dependencies:
  config:
    - image.style.card_1280
    - image.style.card_1800
    - image.style.card_768
    - image.style.card_991
  theme:
    - kingly_minimal
id: card_responsive
label: 'Card (Responsive)'
image_style_mappings:
  -
    breakpoint_id: kingly_minimal.lg
    multiplier: 1x
    image_mapping_type: media_query
    image_mapping: card_1280
  -
    breakpoint_id: kingly_minimal.md
    multiplier: 1x
    image_mapping_type: media_query
    image_mapping: card_991
  -
    breakpoint_id: kingly_minimal.sm
    multiplier: 1x
    image_mapping_type: media_query
    image_mapping: card_768
  -
    breakpoint_id: kingly_minimal.xl
    multiplier: 1x
    image_mapping_type: media_query
    image_mapping: card_1800
fallback_image_style: card_768
